### ISSUE TITLE
Suggestions concerning the world map

### ISSUE THREAD

**Issue by Rahmsauce** [BrianRuizy/covid19-dashboard#55]
I have some suggestions concerning the way data is displayed on the world map as well as its performance:

1) Comparability of markers
Currently, some markers on the map show the number of cases in a country (e.g. South Korea, UK, France) whereas others only represent the number of cases in a specific region of a country (e.g. in Japan, Germany, US). This results in the markers not being very well comparable to each other. This problem could be solved by summarizing the numbers of cases of all regions of each country and displaying them as a single marker.

2) Loading times
The largest bottleneck of the website is Plotly.js. Loading this file asynchronously is likely to result in a considerable performance boost. However, this is currently not possible because the world map is processed by the server, which requires the client to load Plotly.js before the page finishes loading. To allow Plotly.js to be loaded asynchronously, the world map needs to be processed on the client.

**Comment by BrianRuizy** [comment]
> 1. Comparability of markers

One bullet 1, it is something I've come to consider because it skews the true comparison of the visualization among countries. I had decided to just wait it out, because JHU is constantly updating the datasets. Some months back there was no data on South American cities and now there's plenty.

So again, unless we could source other countries' data, I would say leave it as such.


>2.  Loading times

I'm open to whatever change you deem appropriate on this!

**Comment by Rahmsauce** [comment]
Alright. I'm going to start working on improving the loading times then.

**Comment by BrianRuizy** [comment]
#57, thanks to @Rahmsauce
